### ISSUE TITLE
Autoreport-tabell

### ISSUE THREAD

**Issue by lenaringstado** [Rapporteket/rapbase#103]
Er det mulig å få inn ei (eller flere) ekstra kolonner i autoReportTable, f.eks. basert på param? Hvilken kan f.eks. velges ut fra paramName. Antar det vil kreve en ekstra inn-parameter til funksjonen.
Mange rapporter har andre valg/inngangsparametre enn egen reshid og for disse er det nødvendig å vise hvilket utvalg rapporten er bestilt for.

**Comment by areedv** [comment]
`autoReport` i `rapbase` er et sett av funksjoner som skal gi mulighet for bruk av shiny elementer (moduler) ifm utsending for alle registre. Både implementasjon i registre (bruk) og vedlikehold av koden er "medium" komplisert blant annet for å sikre generelle egenskaper slik at anvendelse kan skje på tvers av registre. En endring i slike felleskomponenter påvirker alle som har tatt slikt i bruk. Med økt kompleksitet kommer også en økt risiko for feil som når de opptrer vil få en større konsekvens fordi mange registre har samme komponent i bruk. Å holde kompleksiteten lav er derfor spesielt viktig her. Etablering av "vilkårlige kolonner" i tabellen vil føre til økt kompleksitet og jeg ønsker derfor ikke en slik endring av `autoReport` i `rapbase`.

Et alternativ til løsning er å lage en annen variant av `autoReport` med mer fleksibilitet/kompleksitet slik at registrene har et reelt valg av "risikoprofil" når de tar i bruk felleskomponenter. Om jeg/vi har kapasitet til å vedlikeholde noe slikt er en annen vurdering.

Et annet alternativ er å etablere registerspesifikke implementasjoner der man selvfølgelig har all mulig frihet til å lage ting akkurat slik man vil ha det, både hva funksjonalitet og risiko angår. Koden som inngår er `autoReport` er skvær R og Shiny og kan selvfølgelig gjenbrukes ved slik spesifikk implementasjon.
