### ISSUE TITLE
Fil som via kommune og bydelsnummer knytter hver pasient til et boområde

### ISSUE THREAD

**Issue by lenaringstado** [Rapporteket/rapbase#13]
Legge til fil med variablene: 
kommunenummer, bydelsnummer, boHF, boRHF, fylke, årstall, antall innbyggere, evt. kjønn og alder(sgrupper).
Fila skal benyttes til å koble slik at resultater kan vises ut fra et boperspektiv. Og evt. ha mulighet til å justere for alder og kjønn.

**Comment by areedv** [comment]
Noen (les @lenaringstado ) må lage fila, eller aller helst et R-datasett først

**Comment by areedv** [comment]
Tilsvarende data ligger i "datapakken" [rapsodi](https://github.com/Rapporteket/rapsodi)
