### ISSUE TITLE
Abonnement for selvvalgte e-postadresser

### ISSUE THREAD

**Issue by lenaringstado** [Rapporteket/rapbase#31]
Flere registre (og jeg) ønsker mulighet for å automatisk sende rapporter til e-postadresser vi selv legger inn.

**Comment by areedv** [comment]
```remotes::install_github("Rapporteket/raptools")```
```rapbase::runShinyApp("autoReport", "shinyApps", "raptools")```

Der skal det være mulig å legge til epostmottakere manuelt.

Men, denne applikasjonen er utdatert mtp nåværende status/funksjonalitet for abonnement og trenger derfor oppdatering. Mitt forslag er å utsette arbeid med dette til etter at nytt Rapportek er operasjonelt

**Comment by areedv** [comment]
Saken hører strengt tatt til raptools

**Comment by areedv** [comment]
Now duplicate of #48. Closing this one
