### ISSUE TITLE
Grense på 10 aktive abonnement?

### ISSUE THREAD

**Issue by kevinthon** [Rapporteket/rapbase#41]
Lone på UNN register rapporterer at hun ikke får ha mer enn 10 aktive abonnement i abonnementsfanen til NoRGast. Siden jeg ikke har lagt en slik sperre i NoRGast antar jeg at begrensningen er satt i abonnementsfunksjonene i rapbase.

**Comment by areedv** [comment]
Det er ingen slik grense i rapbase, så vidt jeg vet. norgast bruker vel ```DT::datatable()``` for å fremstille tabellen og det er mulig at standard antall rader er 10 og at man derfor må "bla" i tabellen når antall abonnementer overstiger dette. Antall rader som vises per "tabellside" kan selvfølgelig overstyres. Du kan se et eksempel på akkurat dette i [imongr](https://github.com/mong/imongr/blob/master/R/app_server.R#L58).

**Comment by kevinthon** [comment]
Det var visningen som var problemet, og det kom aldri opp et alternativ for å bla i tabellen når den oversteg 10 rader. En variant av imongr-lenken løste problemet.
