### ISSUE TITLE
loadRegData etterlater åpen forbindelse?

### ISSUE THREAD

**Issue by lenaringstado** [Rapporteket/rapbase#45]
Etter at jeg begynte å bruke loadRegData, får jeg stadig advarsel om at ikke databasekoblinga er stengt:

Warning message:
In for (i in seq_len(n)) { :
  call dbDisconnect() when finished working with a connection

Kan ikke huske at det skjedde ved bruk av LoadRegData. Ser at begge inneholder rapCloseDbConnection. Kanskje sistnevnte er endret?

**Comment by areedv** [comment]
Det burde ikke være noen forskjell... Hvilken funksjon er det som gir denne advarselen?

**Comment by lenaringstado** [comment]
Jeg ser ikke hvilken funksjon som kommer med advarselen. Den kommer etter at jeg har brukt loadRegData. Jeg kjenner ikke igjen kodesnutten det henvises til. (Hverken den forrige eller den under): 
Warning message:
In names(sys.call()) %in% c("", "exact") :
 call dbDisconnect() when finished working with a connection

**Comment by areedv** [comment]
En innsats her krever en reproduserbar feil. Saken må gjerne åpnes igjen når det foreligger
